
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import AdvancedRecommendations from './AdvancedRecommendations';

interface AIPoweredInsightsProps {
  timeRange: string;
}

const AIPoweredInsights: React.FC<AIPoweredInsightsProps> = ({ timeRange }) => {
  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>AI-Powered Insights</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-muted-foreground mb-4">
            Discover actionable insights automatically generated by our AI engine based on your organization's search patterns and content usage.
          </p>
          
          <AdvancedRecommendations timeRange={timeRange} />
        </CardContent>
      </Card>
    </div>
  );
};

export default AIPoweredInsights;
